spring:
  application:
    name: ad-eureka
server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
    prefer-ip-address: false
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
      
